#!/bin/sh

usage(){
    echo "Usage: $0 FILE [schedule [backlog]]"
    echo "Usage: $0 FILE schedule weight [WEIGHT]"
    echo "Usage: $0 FILE schedule random"
    echo "Usage: $0 FILE contact NAME"
}

keepintouch="scala -cp .:$JAR com.dbulysse.keepintouch.Main"

$keepintouch $@
if [ "$?" -ne "0" ]; then
    usage
    exit 1
fi
