#!/bin/sh

usage(){
    echo "Usage: $0 DATAFILE"
    echo "Usage: $0 DATAFILE [schedule [{overdue|backlog|random}]]"
    echo "Usage: $0 DATAFILE contacted NAME"
}

keepintouch="scala -cp .:$JAR com.dbulysse.keepintouch.Main"

$keepintouch $@
if [ "$?" -ne "0" ]; then
    usage
    exit 1
fi
